# Generated by Django 4.1.5 on 2023-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(max_length=100)),
                ('pose_type', models.ManyToManyField(to='poses.posetype')),
            ],
            options={
                'verbose_name_plural': 'Poses',
            },
        ),
    ]
