# Generated by Django 4.1.5 on 2023-02-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poses',
            old_name='english_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='poses',
            old_name='pose_type',
            new_name='types',
        ),
        migrations.AddField(
            model_name='poses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
