# Generated by Django 4.1.5 on 2023-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
