# Generated by Django 4.1.5 on 2023-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_alter_yogaimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
