# Generated by Django 4.1.5 on 2023-02-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
